sheets:
	openscad-nightly -o ./sheet_1_of_3.dxf sheet_1_of_3.scad
	openscad-nightly -o ./sheet_2_of_3.dxf sheet_2_of_3.scad
	openscad-nightly -o ./sheet_3_of_3.dxf sheet_3_of_3.scad
	openscad-nightly -o ./sheet_1_of_3.svg sheet_1_of_3.scad
	openscad-nightly -o ./sheet_2_of_3.svg sheet_2_of_3.scad
	openscad-nightly -o ./sheet_3_of_3.svg sheet_3_of_3.scad
