sheets:
	openscad-nightly -o clamp.stl           clamp.scad
	openscad-nightly -o clamp_cut_file.dxf  clamp_cut_file.scad
	openscad-nightly -o top_cut_file.dxf    top_cut_file.scad
	openscad-nightly -o bottom_cut_file.dxf bottom_cut_file.scad
